apiVersion: thelastpickle.com/v1alpha1
kind: TLPStress
metadata:
  name: tlpstress-demo
spec:
  stressConfig:
    workload: KeyValue
    partitions: 25m
    duration: 60m
    readRate: "0.3"
    replication:
      networkTopologyStrategy:
        dc1: 2
    partitionGenerator: sequence
  jobConfig:
    parallelism: 1
  cassandraConfig:
    cassandraService: tlpstress-demo 
  image: thelastpickle/tlp-stress:3.0.0
  imagePullPolicy: IfNotPresent
