apiVersion: thelastpickle.com/v1alpha1
kind: TLPStressContext
metadata:
  # There should only be one TLPStressContext per namespace. It must be named
  # tlpstress; otherwise, the controller will ignore it.
  name: tlpstress
  labels:
    env: dev
spec:
  installPrometheus: true
  installGrafana: true
