apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: grafanas.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: Grafana
    listKind: GrafanaList
    plural: grafanas
    singular: grafana
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          properties:
            hostname:
              type: string
              description: Hostname for the ingress. Optional when --openshift is set
            containers:
              type: array
              items:
                type: object
                description: Additional container to add to the grafana pod
            secrets:
              type: array
              items:
                type: string
                description: Secret to be mounted as volume into the grafana deployment
            logLevel:
              type: string
              description: Log level of the grafana instance, defaults to info
            adminUser:
              type: string
              description: Default admin user name
            adminPassword:
              type: string
              description: Default admin password
            basicAuth:
              type: boolean
              description: Basic auth enabled
            disableLoginForm:
              type: boolean
              description: Disable login form
            disableSignoutMenu:
              type: boolean
              description: Disable signout menu
            anonymous:
              type: boolean
              description: Anonymous auth enabled
            config:
              type: object
              description: Grafana config
            createRoute:
              type: boolean
              description: Create an OpenShift Route instead of Ingress
            dashboardLabelSelectors:
              type: array
              items:
                type: object
                description: Label selector or match expressions
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: grafanadashboards.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: GrafanaDashboard
    listKind: GrafanaDashboardList
    plural: grafanadashboards
    singular: grafanadashboard
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        status:
          properties:
            messages:
              type: array
              items:
                description: Dashboard Status Message
                type: object
        spec:
          properties:
            name:
              type: string
            json:
              type: string
            plugins:
              type: array
              items:
                description: Grafana Plugin Object
                type: object
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: grafanadatasources.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: GrafanaDataSource
    listKind: GrafanaDataSourceList
    plural: grafanadatasources
    singular: grafanadatasource
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          required: ["datasources", "name"]
          properties:
            name:
              type: string
              minimum: 1
            datasources:
              type: array
              items:
                description: Grafana Datasource Object
                type: object
        status:
          type: object
