apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: example-grafana-nodeport
spec:
  service:
    labels:
      app: grafana
#    type: NodePort
  config:
    log:
      mode: "console"
      level: "debug"
    security:
      admin_user: "root"
      admin_password: "secret"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.basic:
      enabled: False
    auth.anonymous:
      enabled: True
  dashboardLabelSelector:
    - matchExpressions:
        - {key: app, operator: In, values: [grafana]}
