version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12.5

    working_directory: /home/circleci
    steps:
      - checkout
      - run: make build

      # specify any bash command here prefixed with `run: `
#      - run: go get -v -t -d ./...
#      - run: go test -v ./...
