version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    #    docker:
    #      - image: circleci/golang:1.12.5
    environment:
      - GO111MODULE: on
      - GOLANG_VERSION: 1.12.12
    steps:
      - restore_cache:
          key: operator-sdk-v0.9.0
          paths:
            - /tmp/operator-sdk
      - run:
          name: install golang
          command: |
            GOROOT=$(go env GOROOT)
            sudo rm -r $(go env GOROOT)
            sudo mkdir $GOROOT
            curl https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz | sudo tar xz -C $GOROOT --strip-components=1
      - run:
          name: install operator-sdk
          command: |
            echo "Installing Operator SDK"
            curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.9.0/operator-sdk-v0.9.0-x86_64-linux-gnu && chmod +x operator-sdk && sudo mv operator-sdk /usr/local/bin/
      - checkout
      #      - setup_remote_docker
      #      - attach_workspace:
      #          at: .
      - run: make unit-test
      - run: make build-image
      - deploy:
          name: Push image to docker hub
          command: |
            docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASSWORD
            make push-image
#  unit-test:
#    docker:
#      - image: circleci/golang:1.12.5
#    steps:
#      - run: make unit-test
#  publish-latest:
#    machine:
#      image: ubuntu-1604:201903-01
#    docker:
#      - image: circleci/golang:1.12.5
#    steps:
#      - setup_remote_docker
#      - deploy:
#          name: Push image to docker hub
#          command: |
#            docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASSWORD
#            make push-image
#  e2e-tests:
#    docker:
#      - image: circleci/golang:1.12.5
#    steps:
#      - run: ./scripts/kind-smoketest.sh


#workflows:
#  version: 2.1
#  build-master:
#    jobs:
#      - build:

#          filters:
#            branches:
#              only: master
