version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -d github.com/operator-framework/operator-sdk@0.9.0
      - run: make code-gen
      - run: make openapi-gen
      - run: make build-image
  unit-test:
    docker:
      - image: circleci/golang:1.12.5
    steps:
      - run: make unit-test
  publish-latest:
    docker:
      - image: circleci/golang:1.12.5
    steps:
      - setup_remote_docker
      - deploy:
          name: Push image to docker hub
          command: |
            docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASSWORD
            make push-image
  e2e-tests:
    docker:
      - image: circleci/golang:1.12.5
    steps:
      - run: ./scripts/kind-smoketest.sh


#workflows:
#  version: 2.1
#  build-master:
#    jobs:
#      - build:

#          filters:
#            branches:
#              only: master