apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tlpstresses.thelastpickle.com
spec:
  group: thelastpickle.com
  names:
    kind: TLPStress
    listKind: TLPStressList
    plural: tlpstresses
    singular: tlpstress
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            cassandraCluster:
              type: object
            cassandraService:
              type: string
            concurrency:
              format: int32
              type: integer
            consistencyLevel:
              enum:
              - ANY
              - ONE
              - TWO
              - THREE
              - QUORUM
              - ALL
              - LOCAL_QUORUM
              - EACH_QUORUM
              - SERIAL
              - LOCAL_SERIAL
              - LOCAL_ONE
              type: string
            dataCenter:
              type: string
            dropKeyspace:
              type: boolean
            duration:
              type: string
            image:
              type: string
            imagePullPolicy:
              type: string
            iterations:
              pattern: ^(\d+)([BbMmKk]?$)
              type: string
            partitionGenerator:
              type: string
            partitions:
              pattern: ^(\d+)([BbMmKk]?$)
              type: string
            populate:
              pattern: ^(\d+)([BbMmKk]?$)
              type: string
            readRate:
              type: string
            replication:
              properties:
                networkTopologyStrategy:
                  additionalProperties:
                    format: int32
                    type: integer
                  type: object
                simpleStrategy:
                  format: int32
                  type: integer
              type: object
            workload:
              enum:
              - KeyValue
              - BasisTimeSeries
              - CountersWide
              - LWT
              - Locking
              - Maps
              - MaterializedViews
              - RandomPartitionAccess
              - UdtTimeSeries
              type: string
          required:
          - workload
          - cassandraService
          - image
          - imagePullPolicy
          type: object
        status:
          properties:
            jobStatus:
              type: object
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
