kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
- role: worker
  extraPortMappings:
  - containerPort: 3000
    hostPort: 3500
    listenAddress: "127.0.0.1"
    protocol: tcp
